services:
  bot:
    build: tyrannicodin/tcg-bot:latest
    restart: always
    volumes:
      - bot-persist:/persistent
      - type: bind
        source: ./servers
        target: /servers
    env_file:
      - .env

volumes:
  bot-persist:
